Web/800Plumber/Plumber/Areas/Admin/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Plumber.Models;

namespace Plumber.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrator,ContentManager")]
    public class CitiesController : Controller
    {
        private PlumberContext db = new PlumberContext();

        //
        // GET: /Admin/Cities/

        public ViewResult Index(int? id)
        {
            if (id.HasValue)
            {
                var location = db.Location.Find(id);
                ViewBag.SelectedLocation = location.LocationName;
                ViewBag.SelectedLocationId = location.LocationId;
                var cityserved = db.CityServed.Include(c => c.Location).Where(c => c.LocationId == id);
                return View(cityserved.ToList());
            }
            return View("Error");
        }

        ////
        //// GET: /Admin/Cities/Details/5

        //public ViewResult Details(int id)
        //{
        //    CityServed cityserved = db.CityServed.Find(id);
        //    return View(cityserved);
        //}

        //
        // GET: /Admin/Cities/Create

        public ActionResult Create(int id)
        {
            ViewBag.LocationId = id;
            return View();
        } 

        //
        // POST: /Admin/Cities/Create

        [HttpPost]
        public ActionResult Create(int id, CityServed cityserved)
        {
            if (ModelState.IsValid)
            {
                cityserved.LocationId = id;
                db.CityServed.Add(cityserved);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = id });  
            }

            ViewBag.LocationId = new SelectList(db.Location, "LocationId", "LocationName", cityserved.LocationId);
            return View(cityserved);
        }
        
        ////
        //// GET: /Admin/Cities/Edit/5
 
        //public ActionResult Edit(int id)
        //{
        //    CityServed cityserved = db.CityServed.Find(id);
        //    ViewBag.LocationId = new SelectList(db.Location, "LocationId", "LocationName", cityserved.LocationId);
        //    return View(cityserved);
        //}

        ////
        //// POST: /Admin/Cities/Edit/5

        //[HttpPost]
        //public ActionResult Edit(CityServed cityserved)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(cityserved).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.LocationId = new SelectList(db.Location, "LocationId", "LocationName", cityserved.LocationId);
        //    return View(cityserved);
        //}

        //
        // GET: /Admin/Cities/Delete/5
 
        public ActionResult Delete(int id)
        {
            CityServed cityserved = db.CityServed.Find(id);
            return View(cityserved);
        }

        //
        // POST: /Admin/Cities/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            CityServed cityserved = db.CityServed.Find(id);
            db.CityServed.Remove(cityserved);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = cityserved.LocationId });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Web/800Plumber/Plumber/Areas/Admin/Views/Cities/Create.cshtml
@model Plumber.Models.CityServed

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Add a new city</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        @*<legend>CityServed</legend>*@

        @*<div class="editor-label">
            @Html.LabelFor(model => model.LocationId, "Location")
        </div>
        <div class="editor-field">
            @Html.DropDownList("LocationId", String.Empty)
            @Html.ValidationMessageFor(model => model.LocationId)
        </div>*@

        <div class="editor-label">
            @Html.LabelFor(model => model.City)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.City)
            @Html.ValidationMessageFor(model => model.City)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Cities", new { id = ViewBag.LocationId }, null)
</div>

Web/800Plumber/Plumber/Areas/Admin/Views/Cities/Delete.cshtml
@model Plumber.Models.CityServed
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>
    confirm delete</h2>
<h3>
    Are you sure you want to delete the city @Model.City for the location @Model.Location.LocationName?</h3>
@using (Html.BeginForm())
{
    <p>
        <input type="submit" value="Delete" />
        |
        @Html.ActionLink("Back to List", "Index", new { id = Model.LocationId })
    </p>
}

Web/800Plumber/Plumber/Areas/Admin/Views/Cities/Index.cshtml
@model IEnumerable<Plumber.Models.CityServed>
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>
    Manage cities for @ViewBag.SelectedLocation</h2>
<p>
    @Html.ActionLink("Add a new city", "Create", new { id = ViewBag.SelectedLocationId })
</p>
<table class="data-table" id="citiesTable">
<thead>
    <tr>
        <th>
            City served
        </th>
        <th>
        </th>
    </tr>
    </thead>
    <tbody>
    @if (Model.Count() > 0)
    {
        foreach (var item in Model)
        {
        <tr>
            <td style="width: 95%">
                @Html.Raw(item.City)
            </td>
            <td style="text-align: center">
                @Ajax.ImageActionLink(Url.Content("~/Content/admin_icons/delete.gif"), "Delete", new { id = item.CityServedId }, null, null)
            </td>
        </tr>
        }
    }
    else
    {
        <tr>
            <td style="width: 100%" colspan="2">
                <img src="../../../../Content/admin_icons/warning.png" alt="" title="No city found for the selected location" /><br />
                <strong>No City found for the selected Location!</strong>
            </td>
        </tr>
    }
    </tbody>
    <tfoot>
        <tr id="pager">
            <td colspan="2">
                <img src="@Url.Content("~/Content/_assets/img/first.png")" alt="" class="first"/>
                <img src="@Url.Content("~/Content/_assets/img/prev.png")" alt="" class="prev"/>
                <input class="pagedisplay" type="text" />
                <img src="@Url.Content("~/Content/_assets/img/next.png")" alt="" class="next"/>
                <img src="@Url.Content("~/Content/_assets/img/last.png")" alt="" class="last"/>
                <select class="pagesize">
                    <option selected="selected" value="10">10</option>
                    <option value="20">20</option>
                    <option value="30">30</option>
                    <option value="40">40</option>
                </select>
            </td>
        </tr>
    </tfoot>
</table>
<p>
    @Html.ActionLink("Back to location details", "Details", "Location", new { id = ViewBag.SelectedLocationId, area = "Admin" }, null)
    |
    @Html.ActionLink("Back to locations list", "Index", "Location")
</p>
<script type="text/javascript">
    $(document).ready(function () {
        $("#citiesTable")
        .tablesorter({ widgets: ['zebra'] })
        .tablesorterPager({ container: $("#pager"), positionFixed: false })
    });
</script>
@section Scripts{
    <link href="@Url.Content("~/Content/_assets/themes/yui/style.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Content/_assets/js/jquery.tablesorter-2.0.3.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/_assets/js/jquery.tablesorter.filer.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/_assets/js/jquery.tablesorter.pager.js")" type="text/javascript"></script>
}