Web/SiteBlue/Areas/MyCalls/Controllers/CallStatisticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DHTMLX.Export.Excel;
using SiteBlue.Areas.MyCalls.Models;
using SiteBlue.Business;
using SiteBlue.Controllers;
using SiteBlue.Data;
using System.Data.Linq;
using System.Web.Security;

namespace SiteBlue.Areas.MyCalls.Controllers
{
    [Authorize]
    public class CallStatisticController : SiteBlueBaseController
    {
        //
        // GET: /MyCalls/CallStatistic/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult DownloadDetailStatistic()
        {
            var generator = new ExcelWriter();
            var xml = Request.Form["grid_xml"];
            xml = Server.UrlDecode(xml);
            var stream = generator.Generate(xml);

            return File(stream.ToArray(), generator.ContentType, "Statistic.xlsx");
        }

        public ActionResult DownloadFullStatistic(int? fr)
        {
            var generator = new ExcelWriter();
            var context = new IncomingCallsQAEntities();

            var statisticlist = (from s in context.StatisticTracks
                                 join ls in context.LookupScripts on s.CalledNumber equals ls.LookupPhoneNr into tls
                                 from ls in tls.DefaultIfEmpty()
                                 join eo in context.EndCallOptions on s.OptionId equals eo.OptionId into teo
                                 from eo in teo.DefaultIfEmpty()
                                 where s.CalledNumber != ""
                                 select new
                                 {
                                     seqnr = s.TrackId,
                                     calltime = s.StartDate,
                                     s.CalledNumber,
                                     s.DialedNumber,
                                     s.Duration,
                                     s.Jobid,
                                     s.UserId,
                                     ls.XMLCode,
                                     eo.OptionName
                                 }).OrderBy(q => q.seqnr);

            var xml = "<rows><head><columns>";
            xml += "<column width='50' type='ch' align='center' color='white' sort='int'>Sequence</column>";
            xml += "<column width='150' type='ch' align='center' color='white' sort='date'>Call Time</column>";
            xml += "<column width='100' type='ch' align='center' color='white' sort='str'>Called Number</column>";
            xml += "<column width='100' type='ch' align='center' color='white' sort='str'>Dialed Number</column>";
            xml += "<column width='80' type='ch' align='center' color='white' sort='str'>Duration</column>";
            xml += "<column width='80' type='ch' align='center' color='white' sort='str'>JobID</column>";
            xml += "<column width='100' type='ch' align='center' color='white' sort='str'>User Name</column>";
            xml += "<column width='100' type='ch' align='center' color='white' sort='str'>XML Code</column>";
            xml += "<column width='100' type='ch' align='center' color='white' sort='str'>Option Name</column></columns></head>";

            foreach (var row in statisticlist)
            {
                xml += "<row id='" + row.seqnr + "'>";
                xml += "<cell><![CDATA[" + row.seqnr + "]]></cell>";
                xml += "<cell><![CDATA[" + row.calltime + "]]></cell>";
                xml += "<cell><![CDATA[" + row.CalledNumber + "]]></cell>";
                xml += "<cell><![CDATA[" + row.DialedNumber + "]]></cell>";
                xml += "<cell><![CDATA[" + row.Duration + "]]></cell>";
                xml += "<cell><![CDATA[" + row.Jobid + "]]></cell>";
                xml += "<cell><![CDATA[" + Membership.GetUser(row.UserId).UserName + "]]></cell>";
                xml += "<cell><![CDATA[" + row.XMLCode + "]]></cell>";
                xml += "<cell><![CDATA[" + row.OptionName + "]]></cell>";
                xml += "</row>";
            }
            xml += "</rows>";

            var stream = generator.Generate(xml);

            return File(stream.ToArray(), generator.ContentType, "FullStatistic.xlsx");
        }

        public ActionResult GetInfoForGrid(DateTime? start, DateTime? end, int? fr, int? opt)
        {
            if (!start.HasValue)
                start = new DateTime(2011, 1, 1);

            if (!end.HasValue)
                end = DateTime.Now;

            var franchisesId = GetFranchisesID(fr ?? -1);
            
            var endCallOptions = GetEndCallOptions();
            
            var dic = new Dictionary<InfoNumber, List<KeyValuePair<string, int>>>();

            if (opt != null && opt.Value == 2)
                dic = GetDicOfCallTalkerStat(start, end, franchisesId);
            else
                dic = GetDicOfPhoneStat(start, end, franchisesId);

            var model = new GridModel()
            {
                GridData = dic,
                opt = opt,
                Header = new GridHeader() { Options = endCallOptions }
            };

            return View(model);
        }

        private List<int> GetFranchisesID(int fr)
        {
            var franchisesId = new List<int>();

            if (fr == 0)
                franchisesId = UserInfo.Franchises.Select(i => i.FranchiseID).ToList();
            else
                franchisesId.Add(UserInfo.CurrentFranchise.FranchiseID);

            return franchisesId;
        }

        private Dictionary<InfoNumber, List<KeyValuePair<string, int>>> GetDicOfPhoneStat(DateTime? start, DateTime? end, ICollection<int> franchisesId)
        {
            var context = new IncomingCallsQAEntities();

            var EmptyGuid = Guid.Empty;

            var numbersInfos =
                context.Tbl_scriptToFranchiseID.Where(item => franchisesId.Contains(item.FranchiseID)).Select(
                    item =>
                    new InfoNumber
                        {
                            Description = item.LookupScript.XMLCode,
                            PhoneNumber = item.LookupScript.LookupPhoneNr.Remove(0, 1),
                            UserId = EmptyGuid
                        }).
                    ToList();

            var numbers = numbersInfos.Select(i => i.PhoneNumber);
            
            var dic = new Dictionary<InfoNumber, List<KeyValuePair<string, int>>>();
            var stat =
                context.StatisticTracks.Where(
                    item => numbers.Contains(item.CalledNumber) && item.StartDate >= start.Value && item.StartDate < end.Value).
                    GroupBy(i => i.CalledNumber).
                    ToList();

            
            foreach (var number in stat)
            {
                dic.Add(numbersInfos.First(i => i.PhoneNumber == number.Key),
                        number.GroupBy(i => i.EndCallOption != null ? i.EndCallOption.OptionName : "Unknow").Select(
                            i => new KeyValuePair<string, int>(i.Key, i.Count())).ToList());
            }

            return dic;
        }

        private Dictionary<InfoNumber, List<KeyValuePair<string, int>>> GetDicOfCallTalkerStat(DateTime? start, DateTime? end, ICollection<int> franchisesId)
        {
            var context = new IncomingCallsQAEntities();

            var EmptyGuid = Guid.Empty;

            var PhoneNumbers = 
                context.Tbl_scriptToFranchiseID.Where(item => franchisesId.Contains(item.FranchiseID)).Select(
                    item =>
                    new InfoNumber
                    {
                        Description = item.LookupScript.XMLCode,
                        PhoneNumber = item.LookupScript.LookupPhoneNr.Remove(0, 1),
                        UserId = EmptyGuid
                    }).
                    ToList();

            var objmodcommon = new mod_common(new Guid());

            var numbersInfos =
                PhoneNumbers.Select(
                    item =>
                    new InfoNumber
                    {
                        Description = item.Description,
                        PhoneNumber = item.PhoneNumber,
                        UserId = objmodcommon.GetCallTalkerUserID(item.PhoneNumber)
                    }).
                    ToList();

            var users = numbersInfos.Select(i => i.UserId);

            var dic = new Dictionary<InfoNumber, List<KeyValuePair<string, int>>>();
            var stat =
                context.StatisticTracks.Where(
                    item => users.Contains(item.UserId) && item.StartDate >= start.Value && item.StartDate < end.Value).
                    GroupBy(i => i.UserId).
                    ToList();

            foreach (var user in stat)
            {
                dic.Add(numbersInfos.First(i => i.UserId.ToString() == user.Key.ToString()),
                        user.GroupBy(i => i.EndCallOption != null ? i.EndCallOption.OptionName : "Unknow").Select(
                            i => new KeyValuePair<string, int>(i.Key, i.Count())).ToList());
            }
            
            return dic;
        }

        private static List<string> GetEndCallOptions()
        {
            var context = new IncomingCallsQAEntities();

            var endCallOptions = context.EndCallOptions.Select(i => i.OptionName).ToList();
            endCallOptions.Add("Unknow");

            return endCallOptions;
        }
    }
}

Web/SiteBlue/Areas/MyCalls/Views/CallStatisticOld/CallStatistic.cshtml
@model int
@if (Model != 0)
{

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-type">
 <script src="@Url.Content("~/codebase/dhtmlxcommon.js")" type="text/javascript"></script>
    <link rel="STYLESHEET" type="text/css" href="@Url.Content("~/codebase/dhtmlxcombo.css")" />
    <script  src="@Url.Content("~/codebase/dhtmlxcombo.js")" type="text/javascript"></script>  
    <script src="../../../../Scripts/jquery-1.5.1.min.js" type="text/javascript"></script>
    <link rel="STYLESHEET" type="text/css" href="../../../../codebase/dhtmlxgrid.css">
    <link rel="stylesheet" type="text/css" href="../../../../codebase/skins/dhtmlxgrid_dhx_skyblue.css">
    <script src="../../../../codebase/dhtmlxcommon.js" type="text/javascript"></script>
    <script src="../../../../codebase/dhtmlxgrid.js" type="text/javascript"></script>
    <script src="../../../../codebase/dhtmlxgridcell.js" type="text/javascript"></script>
    <script src="../../../../common/dhtmlxgrid_excell_link.js" type="text/javascript"></script>
      @*<script src="@Url.Content("~/Scripts/jquery-1.6.1.min.js")" type="text/javascript"></script>*@

      <link rel="stylesheet" type="text/css" href="../../../../../codebase/dhtmlxcalendar.css">
        </link>
        <link rel="stylesheet" type="text/css" href="../../../../../codebase/skins/dhtmlxcalendar_dhx_skyblue.css">
        </link>
        <script src="../../../../../codebase/dhtmlxcalendar.js"></script>
	   <link href="../../../../codebase/dhtmlxchart.css" rel="stylesheet" type="text/css" /> 
    <script src="../../../../codebase/dhtmlxchart.js" type ="text/javascript"></script>
 
    
</head>
<body style="margin: 0px;">
        <div style="float: left; width: 100%;height:100%; background-color: #d5f1ff">
     <fieldset style="margin-top:20px;color: #1a3b69;font-size: 20px;height:80px">
    @*<legend style="color:#1a3b69">Call Stats</legend>*@
    <div style="color: #d5f1ff;width:100%">
    
    <div style="float:left">   
    </div>
    @*<div style="float:left;padding-top:30px">
       @Html.DropDownList("FranchiseID", new SelectList((List<SiteBlue.Areas.OwnerPortal.Models.Locations>)ViewBag.locations, "LocationID", "LocationName"), "Select a Location Name", new { id = "LocationID" })
    </div>*@
    <div style="margin-left:0px;margin-top:30px">
                        <span style="color: #1a3b69;margin-left:10px" >Call Stats</span>

     <label style="color: #1a3b69;margin-left:400px">
                                Start Date</label>
                            <input type="text" id="calendarfirst" />
                            <label style="color: #1a3b69">
                                End Date</label><input type="text" id="CalendarSecond" />
     <script>
         myCalendar = new dhtmlXCalendarObject(["calendarfirst", "CalendarSecond", "calendar3"]);
         myCalendar.setWeekStartDay(7);
         myCalendar.setDateFormat("%m/%d/%Y");

     </script>
    </div>
    </div>
    </fieldset>
    <div style="padding-top:60px;padding-left :30px; ">
   
    <div id="gridbox"  style="width: 100%; height: 90px; background-color: white; overflow: hidden">
     </div>
       <script>


           mygrid = new dhtmlXGridObject('gridbox');
           mygrid.setImagePath("../../../../codebase/imgs/");
           mygrid.setHeader("Booked,Call Back,Cancelled Call,Corporate Transfer,Hand Up,Not Booked,Owner ,Prank Call,Sales Call,Tech Call,Test,Transfer, Total");
           mygrid.setInitWidths("80,80,120,80,80,80,80,80,80,80,80,80,80");
           mygrid.setColAlign("center,center,center,center,center,center,center,center,center,center,center,center,center");
           mygrid.setColTypes("ed,ed,ed,ed,ed,ed,ed,ed,ed,ed,ed,ed,ed");
           mygrid.setColSorting("txt,txt,txt,txt,txt,txt,txt,txt,txt,txt,txt,txt,txt");
           mygrid.init();

           mygrid.setSkin("dhx_skyblue");
           mygrid.setDateFormat("%Y-%m-%d %H:%i");

           mygrid.loadXML("../../../../common/Xgriddata.xml");
       
       </script>
    </div>
  
    <div style="margin-top:10px;margin-left :260px; ">
    <img src="@Url.Action("InvoiceAging", "CallStatistic")" alt="SimpleChart" />
    <img src="@Url.Action("Legend", "CallStatistic")" alt="SimpleChart"/>
    </div>
    
     @*<iframe src="testdata" width="530px" height="330" style="border: 0px solid black;">
                            </iframe>*@
                   
<div style="height: 150px; margin-left: 15px; font-weight: bold;">
            <a href="@Url.Content("~/MasterData/LandingPage/MyCalls")" title="Back to Dashboard">Back to
                Dashboard</a>
        </div>
     </div>
</body>
</html>
        }
    else
{
    @:<text>No information available</text>
}

Web/SiteBlue/Areas/MyCalls/Views/CallStatisticOld/Index.cshtml
@{
    		ViewBag.Title = "Call Scripts";
    		Layout = "~/Views/Shared/_FranchiseSelectionLayout.cshtml";
}
@section Styles {
    <link rel="STYLESHEET" type="text/css" href="@Url.Content("~/codebase/dhtmlxcombo.css")" />
    <link rel="STYLESHEET" type="text/css" href="../../../../codebase/dhtmlxgrid.css">
    <link rel="stylesheet" type="text/css" href="../../../../codebase/skins/dhtmlxgrid_dhx_skyblue.css">
    <link rel="stylesheet" type="text/css" href="../../../../codebase/dhtmlxcalendar.css"></link>
    <link rel="stylesheet" type="text/css" href="../../../../codebase/skins/dhtmlxcalendar_dhx_skyblue.css"></link>
    <link href="../../../../codebase/dhtmlxchart.css" rel="stylesheet" type="text/css" /> 
}
@section ScriptIncludes {
    <script src="@Url.Content("~/codebase/dhtmlxcommon.js")" type="text/javascript"> </script>
    <script  src="@Url.Content("~/codebase/dhtmlxcombo.js")" type="text/javascript"> </script>  
    <script src="../../../../codebase/dhtmlxcommon.js" type="text/javascript"> </script>
    <script src="../../../../codebase/dhtmlxgrid.js" type="text/javascript"> </script>
    <script src="../../../../codebase/dhtmlxgridcell.js" type="text/javascript"> </script>
    <script src="../../../../common/dhtmlxgrid_excell_link.js" type="text/javascript"></script>
    <script src="../../../../codebase/dhtmlxcalendar.js"></script>
    <script src="../../../../codebase/dhtmlxchart.js" type ="text/javascript"></script>
}
@section InlineScript {
     <script type="text/javascript">
         $('document').ready(function () {
             SiteBlue.renderMenu(true);
             $(SiteBlue).bind("FranchiseChanged", function (e, data) { doOnDataLoad(); });

             doOnDataLoad();
         });

         function doOnDataLoad() {
             mygrid = new dhtmlXGridObject('gridbox');
             mygrid.setImagePath("../../../../codebase/imgs/");
             mygrid.setHeader("Booked,Call Back,Cancelled Call,Corporate Transfer,Hand Up,Not Booked,Owner ,Prank Call,Sales Call,Tech Call,Test,Transfer, Total");
             mygrid.setInitWidths("80,80,120,80,80,80,80,80,80,80,80,80,80");
             mygrid.setColAlign("center,center,center,center,center,center,center,center,center,center,center,center,center");
             mygrid.setColTypes("ed,ed,ed,ed,ed,ed,ed,ed,ed,ed,ed,ed,ed");
             mygrid.setColSorting("txt,txt,txt,txt,txt,txt,txt,txt,txt,txt,txt,txt,txt");
             mygrid.init();

             mygrid.setSkin("dhx_skyblue");
             mygrid.setDateFormat("%Y-%m-%d %H:%i");

             mygrid.loadXML("../../../../common/Xgriddata.xml");
             myCalendar = new dhtmlXCalendarObject(["calendarfirst", "CalendarSecond", "calendar3"]);
             myCalendar.setWeekStartDay(7);
             myCalendar.setDateFormat("%m/%d/%Y");

         }
         
       </script>
    


}
      @*<script src="@Url.Content("~/Scripts/jquery-1.6.1.min.js")" type="text/javascript"></script>*@

        <div style="float: left; width: 100%;height:100%; background-color: #d5f1ff">
     <fieldset style="margin-top:20px;color: #1a3b69;font-size: 20px;height:80px">
    @*<legend style="color:#1a3b69">Call Stats</legend>*@
    <div style="color: #d5f1ff;width:100%">
    
    <div style="float:left">   
    </div>
    @*<div style="float:left;padding-top:30px">
       @Html.DropDownList("FranchiseID", new SelectList((List<SiteBlue.Areas.OwnerPortal.Models.Locations>)ViewBag.locations, "LocationID", "LocationName"), "Select a Location Name", new { id = "LocationID" })
    </div>*@
    <div style="margin-left:0px;margin-top:30px">
                        <span style="color: #1a3b69;margin-left:10px" >Call Stats</span>

     <label style="color: #1a3b69;margin-left:400px">
                                Start Date</label>
                            <input type="text" id="calendarfirst" />
                            <label style="color: #1a3b69">
                                End Date</label><input type="text" id="CalendarSecond" />
   
    </div>
    </div>
    </fieldset>
    <div style="padding-top:60px;padding-left :30px; ">
   
    <div id="gridbox"  style="width: 100%; height: 90px; background-color: white; overflow: hidden">
     </div>
    
    </div>
  
    <div style="margin-top:10px;margin-left :260px; ">
    <img src="@Url.Action("InvoiceAging", "CallStatistic")" alt="SimpleChart" />
    <img src="@Url.Action("Legend", "CallStatistic")" alt="SimpleChart"/>
    </div>
    
     @*<iframe src="testdata" width="530px" height="330" style="border: 0px solid black;">
                            </iframe>*@
                   
<div style="height: 150px; margin-left: 15px; font-weight: bold;">
            <a href="@Url.Content("~/MasterData/LandingPage/MyCalls")" title="Back to Dashboard">Back to Dashboard</a>
        </div>
     </div>