Web/800Plumber/Plumber/Models/Media.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Plumber.Models
{
    [Table("tbl_Media")]
    public class Media
    {
        [Key]
        [ScaffoldColumn(false)]
        public int MediaId { get; set; }

        [DisplayName("Title")]
        [Required(ErrorMessage = "Required")]
        public string Title { get; set; }

        [DisplayName("Sub title")]
        public string SubTitle { get; set; }

        [DisplayName("Content")]
        public string Content { get; set; }

        [DisplayName("Media type")]
        public int? MediaType { get; set; }

        [DisplayName("Extension")]
        public int? MediaExtensionId { get; set; }

        [DisplayName("URL")]
        public string MediaPath { get; set; }

        [DisplayName("Publication date")]
        public DateTime? PublicationDate { get; set; }

        [DisplayName("Archived")]
        public bool IsArchived { get; set; }

        [DisplayName("Deleted")]
        public bool IsDeleted { get; set; }

        public virtual MediaExtension MediaExtension { get; set; }

    }
}

Web/800Plumber/Plumber/Models/TerritoryOwner.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Plumber.Models
{
    [Table("tbl_TerritoryOwner")]
    public class TerritoryOwner
    {
        [Key]
        [ScaffoldColumn(false)]
        public int TerritoryOwnerId { get; set; }

        [DisplayName("Title")]
        [Required(ErrorMessage = "Required")]
        [StringLength(255, ErrorMessage = "Validation error - Length: 255")]
        public string Title { get; set; }

        [DisplayName("Content")]
        [Required(ErrorMessage = "Required")]
        public string Content { get; set; }

        [DisplayName("Image")]
        public string ImageUrl { get; set; }
    }
}

Web/800Plumber/Plumber/Areas/Admin/Controllers/MediaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Plumber.Models;
using System.IO;

namespace Plumber.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrator,ContentManager")]
    public class MediaController : Controller
    {
        private PlumberContext db = new PlumberContext();

        //
        // GET: /Admin/Media/

        public ViewResult Index()
        {
            return View(db.Media.ToList());
        }

        //
        // GET: /Admin/Media/Details/5

        public ViewResult Details(int id)
        {
            Media media = db.Media.Find(id);
            return View(media);
        }

        //
        // GET: /Admin/Media/Create

        public ActionResult Create()
        {
            ViewBag.MediaExtensionId = new SelectList(db.MediaExtension, "MediaExtensionId", "MediaExtensionName");
            return View();
        }

        //
        // POST: /Admin/Media/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Media media, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    if (file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/Uploads"), fileName);
                        file.SaveAs(path);
                        media.MediaPath = string.Format("~/Content/Uploads/{0}", fileName);
                    }
                }
                db.Media.Add(media);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MediaExtensionId = new SelectList(db.MediaExtension, "MediaExtensionId", "MediaExtensionName", media.MediaExtensionId);
            return View(media);
        }

        //
        // GET: /Admin/Media/Edit/5

        public ActionResult Edit(int id)
        {
            Media media = db.Media.Find(id);
            ViewBag.MediaExtensionId = new SelectList(db.MediaExtension, "MediaExtensionId", "MediaExtensionName", media.MediaExtensionId);
            return View(media);
        }

        //
        // POST: /Admin/Media/Edit/5

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Media media, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    if (file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/Uploads"), fileName);
                        file.SaveAs(path);
                        media.MediaPath = string.Format("~/Content/Uploads/{0}", fileName);
                    }
                }
                db.Entry(media).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MediaExtensionId = new SelectList(db.MediaExtension, "MediaExtensionId", "MediaExtensionName", media.MediaExtensionId);
            return View(media);
        }

        //
        // GET: /Admin/Media/Delete/5

        public ActionResult Delete(int id)
        {
            Media media = db.Media.Find(id);
            return View(media);
        }

        //
        // POST: /Admin/Media/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Media media = db.Media.Find(id);
            db.Media.Remove(media);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Web/800Plumber/Plumber/Areas/Admin/Controllers/TerritoryOwnerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Plumber.Models;
using System.IO;

namespace Plumber.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrator,ContentManager")]
    public class TerritoryOwnerController : Controller
    {
        private PlumberContext db = new PlumberContext();

        //
        // GET: /Admin/TerritoryOwner/

        public ViewResult Index()
        {
            return View(db.TerritoryOwners.ToList());
        }

        //
        // GET: /Admin/TerritoryOwner/Details/5

        public ViewResult Details(int id)
        {
            TerritoryOwner territoryowner = db.TerritoryOwners.Find(id);
            return View(territoryowner);
        }

        //
        // GET: /Admin/TerritoryOwner/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Admin/TerritoryOwner/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(TerritoryOwner territoryowner, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    if (file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/Uploads"), fileName);
                        file.SaveAs(path);
                        territoryowner.ImageUrl = string.Format("~/Content/Uploads/{0}", fileName);
                    }
                }
                db.TerritoryOwners.Add(territoryowner);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(territoryowner);
        }
        
        //
        // GET: /Admin/TerritoryOwner/Edit/5
 
        public ActionResult Edit(int id)
        {
            TerritoryOwner territoryowner = db.TerritoryOwners.Find(id);
            return View(territoryowner);
        }

        //
        // POST: /Admin/TerritoryOwner/Edit/5

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(TerritoryOwner territoryowner, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    if (file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/Uploads"), fileName);
                        file.SaveAs(path);
                        territoryowner.ImageUrl = string.Format("~/Content/Uploads/{0}", fileName);
                    }
                }
                db.Entry(territoryowner).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(territoryowner);
        }

        //
        // GET: /Admin/TerritoryOwner/Delete/5
 
        public ActionResult Delete(int id)
        {
            TerritoryOwner territoryowner = db.TerritoryOwners.Find(id);
            return View(territoryowner);
        }

        //
        // POST: /Admin/TerritoryOwner/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            TerritoryOwner territoryowner = db.TerritoryOwners.Find(id);
            db.TerritoryOwners.Remove(territoryowner);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Web/800Plumber/Plumber/Controllers/TerritoryOwnersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Plumber.Models;

namespace Plumber.Controllers
{
    public class TerritoryOwnersController : Controller
    {

        private PlumberContext db = new PlumberContext();
        //
        // GET: /TerritoryOwners/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            var territoryOwner = db.TerritoryOwners.Find(id);
            if (territoryOwner != null)
                return View(territoryOwner);
            else
                throw new HttpException(404, "Not found");
        }

        // Franchise-02
        public ActionResult Owners()
        {
            var territoryOwners = db.TerritoryOwners.ToList();
            return View(territoryOwners);
        }

        // Franchise Vid
        public ActionResult Media()
        {
            return View();
        }

        // Application
        public ActionResult Application()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Application(object model)
        {
            return View();
        }

        public ActionResult TTab()
        {
            return View();
        }

    }
}

Web/800Plumber/Plumber/Views/TerritoryOwners/Details.cshtml
@model Plumber.Models.TerritoryOwner

@{
    ViewBag.Title = "Details";
}
@section Meta{
    <title>Territory Owners of 1800-PLUMBER</title>
    @*<meta name="description" content="" />
    <meta name="keywords" content="" />*@
}

<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td align="left" valign="top">
            <div class="rowtitle">
                @Html.Raw(Model.Title)<br />
            </div>
            <div class="shadeinnerpage">
                @if (Model.ImageUrl != null)
                {
                    <p style="width: 100%;text-align:center"><img src="@Url.Content(Model.ImageUrl)" alt="" style="width:400px" /></p>
                }
                <div class="maincontent">
                    @Html.Raw(Model.Content)
                </div>
                <div class="backbtn">
                    @Html.ActionLink("Go back to territory owners", "Owners", "TerritoryOwners")</div>
            </div>
        </td>
        <td width="10" align="left" valign="top">
            &nbsp;
        </td>
        <td width="260" align="right" valign="top">
            <div class="col-right">
                @Html.Partial("NearestLocation")
            </div>
        </td>
    </tr>
</table>

@section HeaderImage{
    <div class="aboutus">
        <img src="@Url.Content("~/Content/images/to.jpg")" alt="Services" width="1004" height="187" /></div>
}
@section Navigation{
    <div class="navigation">
        <div class="menu bubplastic horizontal orange">
            <ul>
                <li><span class="menu_r"><a href="@Url.Content("~/")" title="1-800-PLUMBER"><span class="menu_ar">home</span></a></span></li>
                <li><span class="menu_r"><a href="@Url.Content("~/Locations")" title="Plumbing Services Locations">
                    <span class="menu_ar">Locations</span></a></span></li>
                <li><span class="menu_r"><a href="@Url.Content("~/Services")" title="Plumbing and Drain CleaningServices"><span class="menu_ar">
                    Services</span></a></span></li>
                <li><span class="menu_r"><a href="@Url.Content("~/AboutUs")" title=" About 1-800-PLUMBER"><span class="menu_ar">About
                    us </span></a></span></li>
                <li class="highlight"><span class="menu_r"><a href="@Url.Content("~/TerritoryOwners")"><span
                    class="menu_ar">Territory Owners</span></a></span></li>
                <li><span class="menu_r"><a href="@Url.Content("~/ContactUs")" title="Contact for Plumbing and Heating air conditioning"><span class="menu_ar">
                    Contact Us</span></a></span></li>
                @if (Request.IsAuthenticated)
                {
                    <li><span class="menu_r"><a href="@Url.Content("~/LandingPage/Dashboard")" title="1-800-PLUMBER Dashboard"><span class="menu_ar">
                        Dashboard</span></a></span></li>
                    <li><span class="menu_r"><a href="@Url.Content("~/SGAccount/LogOff")"><span class="menu_ar">Log Off </span></a></span></li>
                }
                else
                {
                 <li><span class="menu_r"><a href="@Url.Content("~/SGAccount/LogOn")"><span class="menu_ar">Log On </span></a></span></li>
                }
            </ul>
            <br class="clearit" />
        </div>
    </div>
}

Web/800Plumber/Plumber/Views/TerritoryOwners/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@section Meta{
    <title>Territory Owners of 1800-PLUMBER</title>
    @*<meta name="description" content="" />
    <meta name="keywords" content="" />*@
}
<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td align="left" valign="top">
            <div class="rowtitle">
                Information</div>
            <div class="shadeinnerpage">
                <div class="left-column-para">
                    <p>
                        Our brand is over a decade in the making. When you think of the perfect name for
                        a home services business, you know it has to be easy to remember and say exactly
                        what you do. What could be more perfect than 1-800-PLUMBER&reg;. You have the opportunity
                        to own this brand for your entire market. However, it is more than just a powerful
                        brand. In perfecting our model, we spent nearly three full years designing specific
                        systems to address the biggest road blocks to growth for new territory owners.</p>
                    <p>
                        <span class="bluelinks">For more information on owning this brand and how we are
                            <br />
                            transforming the industry...</span><br />
                        <a href="@Url.Content("~/TerritoryOwners/Owners")">
                            <img src="@Url.Content("~/Content/images/ch.gif")" alt="Click" width="84" height="19" border="0" /></a></p>
                </div>
                <div class="fi">
                    <span class="blue-title">Call 1-800-758-6237</span><br />
                    Send us an&nbsp;<span class="bluelinks"><a href="mailto:franchiseinfo@1800plumber.com">email</a></span><a
                        href="mailto:franchiseinfo@1800plumber.com"><br />
                    @*</a>Take our&nbsp;<span class="bluelinks"><a href="@Url.Content("~/TerritoryOwners/Media")">video tour</a></span><a
                        href="@Url.Content("~/TerritoryOwners/Franchise")"><br />*@
                    </a>Fill out an&nbsp;<span class="bluelinks"><a href="@Url.Content("~/TerritoryOwners/Application")">application</a></span>
                </div>
            </div>
        </td>
        <td width="10" align="left" valign="top">
            &nbsp;
        </td>
        <td width="260" align="right" valign="top">
            <div class="col-right">
                @Html.Partial("NearestLocation")
            </div>
        </td>
    </tr>
</table>
@section HeaderImage{
    <div class="aboutus">
        <img src="@Url.Content("~/Content/images/to.jpg")" alt="Services" width="1004" height="187" /></div>
}
@section Navigation{
    <div class="navigation">
        <div class="menu bubplastic horizontal orange">
            <ul>
                <li><span class="menu_r"><a href="@Url.Content("~/")" title="1-800-PLUMBER"><span class="menu_ar">home</span></a></span></li>
                <li><span class="menu_r"><a href="@Url.Content("~/Locations")" title="Plumbing Services Locations">
                    <span class="menu_ar">Locations</span></a></span></li>
                <li><span class="menu_r"><a href="@Url.Content("~/Services")" title="Plumbing and Drain CleaningServices"><span class="menu_ar">
                    Services</span></a></span></li>
                <li><span class="menu_r"><a href="@Url.Content("~/AboutUs")" title=" About 1-800-PLUMBER"><span class="menu_ar">About
                    us </span></a></span></li>
                <li class="highlight"><span class="menu_r"><a href="@Url.Content("~/TerritoryOwners")"><span
                    class="menu_ar">Territory Owners</span></a></span></li>
                <li><span class="menu_r"><a href="@Url.Content("~/ContactUs")" title="Contact for Plumbing and Heating air conditioning"><span class="menu_ar">
                    Contact Us</span></a></span></li>
                @if (Request.IsAuthenticated)
                {
                    <li><span class="menu_r"><a href="@Url.Content("~/LandingPage/Dashboard")" title="1-800-PLUMBER Dashboard"><span class="menu_ar">
                        Dashboard</span></a></span></li>
                    <li><span class="menu_r"><a href="@Url.Content("~/SGAccount/LogOff")"><span class="menu_ar">Log Off </span></a></span></li>
                }
                else
                {
                 <li><span class="menu_r"><a href="@Url.Content("~/SGAccount/LogOn")"><span class="menu_ar">Log On </span></a></span></li>
                }
            </ul>
            <br class="clearit" />
        </div>
    </div>
}

Web/800Plumber/Plumber/Views/TerritoryOwners/Media.cshtml
@{
    ViewBag.Title = "Media";
}
@section Meta{
    <title>Territory Owners of 1800-PLUMBER</title>
    @*<meta name="description" content="" />
    <meta name="keywords" content="" />*@
}
<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td align="left" valign="top">
            <div class="rowtitle">
                Featured Video!
                <br />
            </div>
            <div class="shadeinnerpage">
                @*<video width="690" controls="controls">
                  <source src="@Url.Content("~/Content/video/1800 PLUMBER 5.mov")" type="video/mov" />
                  Your browser does not support the video tag.
                </video>*@
                <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.#version=5,0,30,0" width="320" height="240">
                    <param name="movie" value="@Url.Content("~/Content/video/1800 PLUMBER 6.swf")">
                    <param name="quality" value="best">
                    <param name="play" value="true">
                    <embed pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash"
                                    src="@Url.Content("~/Content/video/1800 PLUMBER 6.swf")" type="application/x-shockwave-flash" width="320" height="240"
                                    quality="best" play="true">
                </object>
            </div>
        </td>
        <td width="10" align="left" valign="top">
            &nbsp;
        </td>
        <td width="260" align="right" valign="top">
            <div class="col-right">
                @Html.Partial("NearestLocation")
            </div>
        </td>
    </tr>
</table>
@section HeaderImage{
    <div class="aboutus">
        <img src="@Url.Content("~/Content/images/to.jpg")" alt="Services" width="1004" height="187" /></div>
}
@section Navigation{
    <div class="navigation">
        <div class="menu bubplastic horizontal orange">
            <ul>
                <li><span class="menu_r"><a href="@Url.Content("~/")" title="1-800-PLUMBER"><span class="menu_ar">home</span></a></span></li>
                <li><span class="menu_r"><a href="@Url.Content("~/Locations")" title="Plumbing Services Locations">
                    <span class="menu_ar">Locations</span></a></span></li>
                <li><span class="menu_r"><a href="@Url.Content("~/Services")" title="Plumbing and Drain CleaningServices"><span class="menu_ar">
                    Services</span></a></span></li>
                <li><span class="menu_r"><a href="@Url.Content("~/AboutUs")" title=" About 1-800-PLUMBER"><span class="menu_ar">About
                    us </span></a></span></li>
                <li><span class="menu_r"><a href="@Url.Content("~/TerritoryOwners")"><span
                    class="menu_ar">Territory Owners</span></a></span></li>
                <li><span class="menu_r"><a href="@Url.Content("~/ContactUs")" title="Contact for Plumbing and Heating air conditioning"><span class="menu_ar">
                    Contact Us</span></a></span></li>
                @if(Request.IsAuthenticated) {
                    <li><span class="menu_r"><a href="@Url.Content("~/LandingPage/Dashboard")" title="1-800-PLUMBER Dashboard"><span class="menu_ar">
                        Dashboard</span></a></span></li>
                    <li><span class="menu_r"><a href="@Url.Content("~/SGAccount/LogOff")"><span class="menu_ar">Log Off </span></a></span></li>
                }
                else
                {
                 <li><span class="menu_r"><a href="@Url.Content("~/SGAccount/LogOn")"><span class="menu_ar">Log On </span></a></span></li>
                }
            </ul>
            <br class="clearit" />
        </div>
    </div>
}

Web/800Plumber/Plumber/Views/TerritoryOwners/Owners.cshtml
@model List<Plumber.Models.TerritoryOwner>
@{
    ViewBag.Title = "Franchise";
}
@section Meta{
    <title>Territory Owners of 1800-PLUMBER</title>
    @*<meta name="description" content="" />
    <meta name="keywords" content="" />*@
}
<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td align="left" valign="top">
                <div class="rowtitle">
                    Three Ways 1-800-PLUMBER is Transforming the Industry<br /></div>
            <div class="shadeinnerpage">
                <div class="maincontent">
                    <p>
                        1-800-PLUMBER&reg; partners with plumbing and HVAC business owners who desire to
                        grow to record profitability or investors seeking a unique, consistent business
                        model. The model is built specifically to initiate quantum growth for existing companies
                        with 3-25 trucks. We work diligently with you to make these visions become reality.
                    </p>
                </div>
                @foreach (var item in Model)
                    {
                    <div class="maincontent">
                        @Html.ActionLink(item.Title, "Details", "TerritoryOwners", new { id = item.TerritoryOwnerId}, null)
                    </div>
                    }
                    <br />
            </div>
            @*<div class="shadeinnerpage">
                <div class="maincontent">
                    <p>1-800-PLUMBER&reg; partners with plumbing and HVAC business
                        owners who desire to grow to record profitability or investors seeking a unique,
                        consistent business model. The model is built specifically to initiate quantum growth
                        for existing companies with 3-25 trucks. We work diligently with you to make these
                        visions become reality. </p>
                    <p>
                        Here are just a few ways we are transforming the industry:</p>
                    <p>
                        The 1-800-PLUMBER&reg; Brand - It is the most valuable brand in the industry. You
                        can spend hundreds of thousands of dollars in marketing and advertising to get your
                        customer to remember your brand... and they still have to look up your phone number.
                        With 1-800-PLUMBER&reg; the name is the number. What could be easier?</p>
                    <p>
                        The Service Center - You have heard of a &ldquo;call center&rdquo;, &ldquo;dispatch
                        center&rdquo; or answering service. We have transformed the industry with a Service
                        Center that has combined all of these in addition to doing many other activities:</p>
                    <ul>
                        <li>"Happy Calls" - every customer receives a short call post-visit to offer you insight
                            on how your technicians performed in the home</li>
                        <li>Technician performance tracking to know exactly where your technicians excel and
                            where they need assistance</li>
                        <li>Tracking exactly where customers find you; the key to determining your marketing
                            strategy</li>
                        <li>GPS tracking to save on fuel and decrease windshield time</li>
                        <li>"Outbound calling to better serve your customers and you" - our Service Center works
                            to fill your calendar with profitable calls</li>
                        <li>24-hour, 7 day a week professional call taking</li>
                        <li>24-hour, 7 day a week job dispatch directly to the appropriate technician via the
                            @Html.ActionLink("t-Tab", "TTab", "TerritoryOwners", null, new { @class = "bluelinks" })</li>
                    </ul>
                    <p>
                        It's more than just a brand you will now own . . . from finding, training and retaining
                        the best technicians in your market to how to most profitably handle inventory,
                        our model will position you to reach your highest and best potential.</p>
                    <p>
                        To find out if your market is available, you can contact us by:</p>
                    <table width="700" border="0" align="left" cellpadding="5" cellspacing="0">
                        <tr>
                            <td align="left" valign="top" style="width:50%;text-align:center">
                                <img src="@Url.Content("~/Content/images/email.gif")" alt="email" width="100" height="93" border="0" />
                            </td>
                            <td align="left" valign="top" style="width:50%; text-align:center">
                                <img src="@Url.Content("~/Content/images/phone.gif")" alt="Phone" width="116" height="93" border="0" />
                            </td>
                        </tr>
                        <tr>
                            <td align="left" valign="top">
                                <strong class="maincontent">Email:</strong> <a href="mailto:franchiseinfo@1800plumber.com"
                                    class="bluelinks">franchiseinfo@1800plumber.com</a>
                            </td>
                            <td align="left" valign="top" class="maincontent">
                                <strong>Phone:</strong> 1-800-PLUMBER (1-800-758-6237)
                            </td>
                        </tr>
                    </table>
                </div>
            </div>*@
        </td>
        <td width="10" align="left" valign="top">
            &nbsp;
        </td>
        <td width="260" align="right" valign="top">
            <div class="col-right">
                @Html.Partial("NearestLocation")
            </div>
        </td>
    </tr>
</table>
@section HeaderImage{
    <div class="aboutus">
        <img src="@Url.Content("~/Content/images/to.jpg")" alt="Services" width="1004" height="187" /></div>
}
@section Navigation{
    <div class="navigation">
        <div class="menu bubplastic horizontal orange">
            <ul>
                <li><span class="menu_r"><a href="@Url.Content("~/")" title="1-800-PLUMBER"><span class="menu_ar">home</span></a></span></li>
                <li><span class="menu_r"><a href="@Url.Content("~/Locations")" title="Plumbing Services Locations"><span class="menu_ar">
                    Locations</span></a></span></li>
                <li><span class="menu_r"><a href="@Url.Content("~/Services")" title="Plumbing and Drain CleaningServices"><span class="menu_ar">
                    Services</span></a></span></li>
                <li><span class="menu_r"><a href="@Url.Content("~/AboutUs")" title=" About 1-800-PLUMBER"><span class="menu_ar">About
                    us </span></a></span></li>
                <li><span class="menu_r"><a href="@Url.Content("~/TerritoryOwners")"><span class="menu_ar">
                    Territory Owners</span></a></span></li>
                <li><span class="menu_r"><a href="@Url.Content("~/ContactUs")" title="Contact for Plumbing and Heating air conditioning"><span class="menu_ar">
                    Contact Us</span></a></span></li>
                @if(Request.IsAuthenticated) {
                    <li><span class="menu_r"><a href="@Url.Content("~/LandingPage/Dashboard")" title="1-800-PLUMBER Dashboard"><span class="menu_ar">
                        Dashboard</span></a></span></li>
                    <li><span class="menu_r"><a href="@Url.Content("~/SGAccount/LogOff")"><span class="menu_ar">Log Off </span></a></span></li>
                }
                else
                {
                 <li><span class="menu_r"><a href="@Url.Content("~/SGAccount/LogOn")"><span class="menu_ar">Log On </span></a></span></li>
                }
            </ul>
            <br class="clearit" />
        </div>
    </div>
}